[mcp_servers.phpstorm]
url = "http://127.0.0.1:64342/stream"

[mcp_servers.phpstorm.tools.build_project]
approval_mode = "approve"

[mcp_servers.phpstorm.tools.create_new_file]
approval_mode = "approve"

[mcp_servers.phpstorm.tools.find_files_by_glob]
approval_mode = "approve"

[mcp_servers.phpstorm.tools.find_files_by_name_keyword]
approval_mode = "approve"

[mcp_servers.phpstorm.tools.get_file_problems]
approval_mode = "approve"

[mcp_servers.phpstorm.tools.get_file_text_by_path]
approval_mode = "approve"

[mcp_servers.phpstorm.tools.get_inspections]
approval_mode = "approve"

[mcp_servers.phpstorm.tools.list_database_connections]
approval_mode = "approve"

[mcp_servers.phpstorm.tools.list_database_schemas]
approval_mode = "approve"

[mcp_servers.phpstorm.tools.list_directory_tree]
approval_mode = "approve"

[mcp_servers.phpstorm.tools.read_file]
approval_mode = "approve"

[mcp_servers.phpstorm.tools.reformat_file]
approval_mode = "approve"

[mcp_servers.phpstorm.tools.replace_text_in_file]
approval_mode = "approve"

[mcp_servers.phpstorm.tools.search_file]
approval_mode = "approve"

[mcp_servers.phpstorm.tools.search_ide_actions]
approval_mode = "approve"

[mcp_servers.phpstorm.tools.search_in_files_by_regex]
approval_mode = "approve"

[mcp_servers.phpstorm.tools.search_in_files_by_text]
approval_mode = "approve"

[mcp_servers.phpstorm.tools.search_regex]
approval_mode = "approve"

[mcp_servers.phpstorm.tools.search_symbol]
approval_mode = "approve"

[mcp_servers.phpstorm.tools.search_text]
approval_mode = "approve"

[mcp_servers.phpstorm.tools.test_database_connection]
approval_mode = "approve"

[mcp_servers.atlassian]
command = "npx"
args = ["-y", "mcp-remote", "https://mcp.atlassian.com/v1/mcp/authv2"]
